### ISSUE TITLE
Missing countries with duplicated adm0 SHPs

### ISSUE THREAD

**Issue by t-downing** [OCHA-DAP/ds-raster-stats#16]
Looks like the raster stats databases (or at least the `seas5` one) is missing countries where the adm0 CODAB from FieldMaps has more than one polygon for adm0. From Confluence looks like this is `BDI`, `NGA`, and `TCD` (of which `NGA` and `TCD` we will be using alot).

Long term fix would be to manage the CODABs ourselves somehow, but short term maybe we could just filter the SHPs from FieldMaps. I know that for `NGA` and `TCD` it's the first row that's correct, but a more robust way to manage this would be to just take whichever one is bigger is a bigger polygon.

**Comment by hannahker** [comment]
@t-downing see https://github.com/OCHA-DAP/ds-raster-stats/pull/17 -- I've dissolved all the admin0 polygons here, since I noticed that some cases have non-overlapping admin 0 polygons.

**Comment by hannahker** [comment]
Closed with #17. @t-downing you should now find the raster stats for these ISO3s in the prod database.
